name: Firebase Deploy (Production)

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 환경변수
    env:
      VITE_KAKAOMAP_API_KEY: ${{ secrets.VITE_KAKAOMAP_API_KEY }}
      VITE_CONTACT_ENDPOINT: ${{ secrets.VITE_CONTACT_ENDPOINT }}
      VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: npm
          cache-dependency-path: package.json

      - name: Install 
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RANDOM_FOOD_STORE }}
          projectId: random-food-store

