name: Firebase Deploy (Production)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install 
        run: |
          npm install

      - name: Create .env for build
        run: |
          cat <<EOF > .env
          VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}
          VITE_CONTACT_ENDPOINT=${{ secrets.VITE_CONTACT_ENDPOINT }}
          VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
          EOF

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RANDOM_FOOD_STORE }}
          projectId: random-food-store
          channelId: live
          
