name: Firebase Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["*"]   # 같은 리포의 PR에만 효과적 (fork PR은 secrets 미전달로 배포 실패)

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Reset npm config for public registry (npm v10 safe)
        run: |
          # CI 홈 디렉토리의 사용자 npmrc를 '공개 레지스트리만' 쓰도록 초기화
          printf "registry=https://registry.npmjs.org/\nfund=false\naudit=false\n" > $HOME/.npmrc

          # 리포 안에 .npmrc가 실수로 커밋돼 있으면 제거(있어도 무시)
          rm -f .npmrc || true

          # 디버그(선택): 현재 레지스트리 확인
          echo "registry:" $(npm config get registry)

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Create .env for build
        run: |
          cat <<EOF > .env
          VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}
          VITE_CONTACT_ENDPOINT=${{ secrets.VITE_CONTACT_ENDPOINT }}
          VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
          EOF

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RANDOM_FOOD_STORE }}
          projectId: random-food-store
          channelId: pr-${{ github.event.number }}
          expires: 7d
